config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resource :search, only: [:show, :create]
  # resource :ticket, only: [:show, :create, :new]
  resources :tickets

  namespace :admin do
    resources :railway_stations do
      patch :update_station_order, on: :member
      patch :update_time, on: :member
    end

    resources :trains do
      resources :cars, shallow: true
    end

    resources :routes
    resources :tickets
  end

  get 'welcome/index'
  root 'searches#show'
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :train

  validates :car_type, :number, presence: true
  validates :number, uniqueness: { scope: :train_id }

  scope :asc, -> { order(:number) }
  scope :desc, -> { order('number DESC') }
  scope :plazkart, -> { where(car_type: 'PlazkartCar') }
  scope :coupe, -> { where(car_type: 'CoupeCar') }
  scope :SV, -> { where(car_type: 'SVCar') }
  scope :seat, -> { where(car_type: 'SeatCar') }

  before_validation :set_number

  private

  def set_number
    numb = Car.where(train_id: train).maximum(:number)
    self.number = numb ? numb + 1 : 1
  end

end

app/controllers/admin/cars_controller.rb
class Admin::CarsController < Admin::BaseController
  before_action :set_car, only: [:show, :edit, :update, :destroy]
  before_action :set_train, only: [:new, :create]

  def index
    @cars = Car.all
  end

  def show
    render "#{@car.car_type}_car.html.erb"
  end

  def new
    @train = Train.find(params[:train_id])
    @car = Car.new
  end

  def edit
  end

  def create
    @car = @train.cars.new(car_params)
    if @car.save
      redirect_to [:admin, @train], notice: 'Car was successfully created.'
    else
      render :new
    end
  end

  def update
    if @car.update(car_params)
      redirect_to [:admin, @car.train], notice: 'Car was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @car.destroy
    redirect_to admin_cars_url, notice: 'Car was successfully destroyed.'
  end

  private
    def set_car
      @car = Car.find(params[:id])
    end

    def set_train
      @train = Train.find(params[:train_id])
    end

    def car_params
      params.require(:car).permit(:number, :car_type, :up_space, :low_space, :side_up_space, :side_low_space, :seat_space)
    end
end

app/views/admin/cars/_car.html.erb
<tr>
  <td>Train - <%= car.train.number %>. Car number - <%= car.number %></td>
  <td><%= link_to 'Show', [:admin,train_car_path(train)] %></td>
  <td><%= link_to 'Edit', edit_admin_train_car_path(car) %></td>
  <td><%= link_to 'Destroy', [:admin,train_car_path], method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/admin/cars/_form.html.erb
<%= form_for [:admin, @train, car] do |f| %>
  <%= render 'common/errors', resource: car %>


  <div class="field">
    <%= f.label :car_type, "Car's type" %>
    <%= f.select :car_type, ["seat", "sv", "plazkart","coupe"] %>
  </div>

  <div id="seat_form">
    <div class="field">
      <%= f.label :seat_space %>
      <%= f.text_field :seat_space %>
    </div>
  </div>

  <div id="sv_form" class="hidden_form">
    <div class="field">
      <%= f.label :low_space %>
      <%= f.text_field :low_space %>
    </div>
  </div>

  <div id="plazkart_form" class="hidden_form">
    <div class="field">
      <%= f.label :up_space %>
      <%= f.text_field :up_space %>
    </div>

    <div class="field">
      <%= f.label :low_space %>
      <%= f.text_field :low_space %>
    </div>

    <div class="field">
      <%= f.label :side_up_space %>
      <%= f.text_field :side_up_space %>
    </div>

    <div class="field">
      <%= f.label :side_low_space %>
      <%= f.text_field :side_low_space %>
    </div>
  </div>

   <div id="coupe_form" class="hidden_form">
    <div class="field">
      <%= f.label :up_space %>
      <%= f.text_field :up_space %>
    </div>

    <div class="field">
      <%= f.label :low_space %>
      <%= f.text_field :low_space %>
    </div>
  </div>






  <div class="actions">
    <%= f.submit "#{car.new_record? ? 'Create' : 'Update' }" %>
  </div>
<% end %>

app/views/admin/cars/coupe_car.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:<%= @car.number %></p></strong>
<p>
  <strong>Type:</strong>
  <%= @car.car_type %>
</p>
<p>
  <strong>Up space count:</strong>
    <%= @car.up_space %>
</p>
<p>
  <strong>Low space count:</strong>
    <%= @car.low_space %>
</p>

<%= link_to 'Edit', edit_admin_car_path(@car) %> |
<%= link_to 'Back', [:admin, @car.train] %>

app/views/admin/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Show', [:admin, @car] %> |
<%= link_to 'Back', [:admin, @car.train] %>

app/views/admin/cars/index.html.erb
<h1>Cars</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @cars %>
  </tbody>
</table>

<br>

<%= link_to 'New Car', new_admin_car_path %>

app/views/admin/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Back', admin_train_cars_path %>

app/views/admin/cars/plazkart_car.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:<%= @car.number %></p></strong>
<p>
  <strong>Type:</strong>
  <%= @car.car_type %>
</p>
<p>
  <strong>Up space count:</strong>
    <%= @car.up_space %>
</p>
<p>
  <strong>Low space count:</strong>
    <%= @car.low_space %>
</p>

<p>
  <strong>Low side space count:</strong>
    <%= @car.side_low_space %>
</p>

<p>
  <strong>Low side uppace count:</strong>
    <%= @car.side_up_space %>
</p>

<%= link_to 'Edit', edit_admin_car_path(@car) %> |
<%= link_to 'Back', [:admin, @car.train] %>

app/views/admin/cars/seat_car.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:<%= @car.number %></p></strong>
<p>
  <strong>Type:</strong>
  <%= @car.car_type %>
</p>
<p>
  <strong>Seat space count:</strong>
    <%= @car.seat_space %>
</p>

<%= link_to 'Edit', edit_admin_car_path(@car) %> |
<%= link_to 'Back', [:admin, @car.train] %>

app/views/admin/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:<%= @car.number %></p></strong>
<p>
  <strong>Type:</strong>
  <%= @car.car_type %>
</p>
<p>
  <strong>Up space count:</strong>
    <%= @car.up_space %>
</p>
<p>
  <strong>Low space count:</strong>
    <%= @car.low_space %>
</p>

<p>
  <strong>Low side space count:</strong>
    <%= @car.side_low_space %>
</p>

<p>
  <strong>Low side uppace count:</strong>
    <%= @car.side_up_space %>
</p>

<p>
  <strong>Seat space count:</strong>
    <%= @car.seat_space %>
</p>

<%= link_to 'Edit', edit_admin_car_path(@car) %> |
<%= link_to 'Back', [:admin, @car.train] %>

app/views/admin/cars/sv_car.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:<%= @car.number %></p></strong>
<p>
  <strong>Type:</strong>
  <%= @car.car_type %>
</p>
<p>
  <strong>Low space count:</strong>
    <%= @car.low_space %>
</p>

<%= link_to 'Edit', edit_admin_car_path(@car) %> |
<%= link_to 'Back', [:admin, @car.train] %>