config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resource :search, only: [:show, :create]
  # resource :ticket, only: [:show, :create, :new]
  resources :tickets

  namespace :admin do
    resources :railway_stations do
      patch :update_station_order, on: :member
      patch :update_time, on: :member
    end

    resources :trains do
      resources :cars, shallow: true
    end

    resources :routes
    resources :tickets
  end

  get 'welcome/index'
  root 'searches#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :train

  validates :car_type, :number, presence: true
  validates :number, uniqueness: { scope: :train_id }

  scope :asc, -> { order(:number) }
  scope :desc, -> { order('number DESC') }
  scope :plazkart, -> { where(car_type: 'PlazkartCar') }
  scope :coupe, -> { where(car_type: 'CoupeCar') }
  scope :SV, -> { where(car_type: 'SVCar') }
  scope :seat, -> { where(car_type: 'SeatCar') }

  before_validation :set_number

  private

  def set_number
    numb = Car.where(train_id: train).maximum(:number)
    self.number = numb ? numb + 1 : 1
  end

end

app/models/coupe_car.rb
class CoupeCar < SvCar
  validates :up_space, presence: true, numericality: { only_integer: true }
end

app/models/plazkart_car.rb
class PlazkartCar < CoupeCar
  validates :side_up_space, :side_low_space, presence: true, numericality: { only_integer: true }
end

app/models/railway_station.rb
class RailwayStation < ApplicationRecord
  has_many :trains
  has_many :railway_stations_routes
  has_many :routes, through: :railway_stations_routes

  validates :title, presence: true
  scope :ordered, -> {
                    joins(:routes).where('routes.id=railway_stations_routes.route_id')
                                  .order('railway_stations_routes.station_order') 
  }

  def update_station_order(route, order)
    temp_station_order = station(route)
    temp_station_order.update(station_order: order) if temp_station_order
  end

  def position_in(route)
    station(route).try(:station_order)
  end

  def update_time(route, arrival, departure)    
    temp_station = station(route)
    temp_station.update(arrival: arrival) if temp_station
    temp_station.update(departure: departure) if temp_station
  end

  def station_time(route, time)
    station(route).try(time)
  end

  protected

  def station(route)
    @station ||= railway_stations_routes.where(route: route).first
  end
end

app/models/railway_stations_route.rb
class RailwayStationsRoute < ApplicationRecord
  belongs_to :railway_station
  belongs_to :route

  validates :railway_station_id, uniqueness: { scope: :route_id }
end

app/models/route.rb
class Route < ApplicationRecord
  has_many :railway_stations_routes
  has_many :railway_stations, through: :railway_stations_routes
  has_many :trains

  validates :name, presence: true
  validate :stations_count


  before_validation :set_name

  # default_scope { joins(:railway_stations_routes) }

  private

  def set_name
    self.name = "#{railway_stations.first.title} - #{railway_stations.last.title}"
  end

  def stations_count
    if railway_stations.size < 2
      errors.add(:base, 'Route should contain at least 2 stations')
    end
  end
end

app/models/search.rb
class Search

  include ActiveModel::Model

  attr_accessor :start_station_id, :end_station_id
  attr_reader :search_result

  def find_start_station
    @start_station ||= RailwayStation.find(start_station_id)
  end

  def find_end_station
    @end_station ||= RailwayStation.find(end_station_id)
  end

  def do_search
    @search_result = Train.includes(route: :railway_stations).where(railway_stations: { id: start_station_id }) &
                     Train.includes(route: :railway_stations).where(railway_stations: { id: end_station_id })
  end

end

app/models/seat_car.rb
class SeatCar < Car
  validates :seat_space, presence: true, numericality: { only_integer: true }
end

app/models/sv_car.rb
class SvCar < Car
  validates :low_space, presence: true, numericality: { only_integer: true }
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user
  belongs_to :train
  belongs_to :start_station, class_name: 'RailwayStation', foreign_key: :start_station_id
  belongs_to :end_station, class_name: 'RailwayStation', foreign_key: :end_station_id

  validates :pas_name, :pas_pasport, presence: true

  after_create :send_notification
  after_destroy :send_notification_destroy

  def route_name
    "#{start_station.title} - #{end_station.title}"
  end

  private

  def send_notification
    TicketsMailer.buy_ticket(self.user, self).deliver_now
  end

  def send_notification_destroy
    TicketsMailer.delete_ticket(self.user, self).deliver_now
  end
end

app/models/train.rb
class Train < ApplicationRecord
  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id
  belongs_to :route
  has_many :tickets
  has_many :cars

  validates :number, presence: true

  private

  # where shoul we use it in our app?
  # in view?
  def count_type_place(type, space_type)
    count = Car.where(car_type: "#{type}").sum(:space_type)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :validatable
  has_many :tickets

  validates :first_name, :second_name, presence: true
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin


  protected

  def check_admin
    redirect_to root_path, alert: 'You havent got rights for this page' unless current_user.admin?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :confifure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    if current_user.admin?
      root_path
    else
      search_path
    end
  end

  protected

  def confifure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :second_name])
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def show
    @search ||= Search.new
  end

  def create
    @search = Search.new(search_params)
    @search.do_search
    render :show
  end

  protected

  def search_params
    params.require(:search).permit(:start_station_id, :end_station_id)
  end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!, only: :create
  before_action :hidden_params, only: [:new]
  before_action :set_ticket, only: [:show]

  def index
    @tickets = current_user.tickets
  end

  def show
  end

  def create
    @ticket = current_user.tickets.new(ticket_params)
    if @ticket.save
      redirect_to @ticket
    else
      render :new
    end
  end

  def new
    @ticket = Ticket.new(train_id: params[:train_id], start_station_id: params[:start_station_id], end_station_id: params[:end_station_id])
  end

  def destroy
    set_ticket.destroy
    redirect_to tickets_path, notice: 'Ticket was successfully destroyed.'
  end

  private

  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  def ticket_params
    params.require(:ticket).permit(:train_id, :start_station_id, :end_station_id, :pas_name, :pas_pasport)
  end

  def hidden_params
    @train = Train.find(params[:train_id])
    @start_station = RailwayStation.find(params[:start_station_id])
    @end_station = RailwayStation.find(params[:end_station_id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/railway_stations_helper.rb
module RailwayStationsHelper
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/searches/show.html.erb
<h1>SEARCH TICKET</h1>

<div class="row">
  <%= form_for(@search, method: :post , url: search_path, html: { class: 'search_form'}) do |f| %>
  <div class="col-md-4">
    <%= f.label :start_station_id, "Start station", class: 'form-control-label' %>
    <%= f.collection_select :start_station_id, RailwayStation.all, :id, :title %>
  </div>

   <div class="col-md-4">
    <%= f.label :end_station_id, "End station" , class: 'form-control-label' %>
    <%= f.collection_select :end_station_id, RailwayStation.all, :id, :title %>
  </div>
  <div class="col-md-4">
    <%= f.submit 'Search' , class: 'btn btn-primary find'%>
  </div>


  <% if @search.search_result %>
    <table class="table table-bordered">
      <thead>
        <tr>
          <td>Train</td>
          <td>Route</td>
          <td>Departure time</td>
          <td>Arrival time</td>
        </tr>
      </thead>
      <tbody>
        <% @search.search_result.each do |res| %>
        <tr>
          <td><%= res.number %></td>
          <td><%= res.route.name %></td>
          <td><%= @search.find_start_station.station_time(res.route, :departure) %></td>
          <td><%= @search.find_end_station.station_time(res.route, :arrival) %></td>
          <td>
            <% if current_user.admin? %>
              <%= form_tag new_admin_ticket_path, method: :get do %>
                <%= hidden_field_tag :train_id, res.id %>
                <%= hidden_field_tag :start_station_id, @search.start_station_id %>
                <%= hidden_field_tag :end_station_id, @search.end_station_id %>
                <%= submit_tag "Buy ticket", class: 'btn btn-default btn-sm' %>
              <% end %>
            <% else %>
              <%= form_tag new_ticket_path, method: :get do %>
                <%= hidden_field_tag :train_id, res.id %>
                <%= hidden_field_tag :start_station_id, @search.start_station_id %>
                <%= hidden_field_tag :end_station_id, @search.end_station_id %>
                <%= submit_tag "Buy ticket", class: 'btn btn-primary btn-sm' %>
              <% end %>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
<% end %>
</div>

app/views/welcome/index.html.erb
<h1>Hello, Rails</h1>
<%= link_to "Stations list", admin_railway_stations_path %>
<%= link_to "Trains list", admin_trains_path %>
<%= link_to "Routes list", admin_routes_path %>
<%= link_to t('admin.tickets.show.to_tickets_list'), admin_tickets_path %>