config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resource :search, only: [:show, :create]
  # resource :ticket, only: [:show, :create, :new]
  resources :tickets

  namespace :admin do
    resources :railway_stations do
      patch :update_station_order, on: :member
      patch :update_time, on: :member
    end

    resources :trains do
      resources :cars, shallow: true
    end

    resources :routes
    resources :tickets
  end

  get 'welcome/index'
  root 'searches#show'
end

app/models/train.rb
class Train < ApplicationRecord
  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id
  belongs_to :route
  has_many :tickets
  has_many :cars

  validates :number, presence: true

  private

  # where shoul we use it in our app?
  # in view?
  def count_type_place(type, space_type)
    count = Car.where(car_type: "#{type}").sum(:space_type)
  end
end

app/controllers/admin/trains_controller.rb
class Admin::TrainsController < Admin::BaseController
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  def index
    @trains = Train.all
  end

  def show
  end

  def new
    @train = Train.new
  end

  def edit
  end

  def create
    @train = Train.new(train_params)
    if @train.save
      redirect_to [:admin, @train], notice: 'Train was successfully created.'
    else
      render :new
    end
  end

  def update
    if @train.update(train_params)
      redirect_to admin_trains_path, notice: 'Train was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @train.destroy
    redirect_to admin_trains_path, notice: 'Train was successfully destroyed.'
  end

  private
    def set_train
      @train = Train.find(params[:id])
    end

    def train_params
      params.require(:train).permit(:number, :current_station_id, :route_id)
    end
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/admin/trains/_form.html.erb
<%= form_for([:admin, train], html: {style: "display: #{hidden ? 'none' : 'block'}" }) do |f| %>
  <%= render 'common/errors', resource: train %>
  <div class="field">
    <%= f.label :number %>
    <%= f.text_field :number %>
  </div>

  <div class="field">
    <%= f.label :current_station %>
    <%= f.collection_select :current_station_id, RailwayStation.all, :id, :title %>
  </div>

  <div class="field">
    <%= f.label :route, "Train's route" %>
    <%= f.collection_select :route_id, Route.all, :id, :name %>
  </div>

  <div class="actions">
    <%= f.submit "#{train.new_record? ? 'Create' : 'Update' }" %>
  </div>
<% end %>

app/views/admin/trains/_train.html.erb
<tr>
  <td>
    <div id="route_title_<%= train.id %>">
      <%= train.number %>
    </div>
    <%= render 'form', train: train, hidden: true %>
  </td>
  <td><%= link_to 'Show', [:admin, train] %></td>
  <td><%= link_to 'Edit', '', class: 'edit_train', data: { train_id: train.id } %></td>
  <td><%= link_to 'Destroy', [:admin, train], method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/admin/trains/edit.html.erb
<h1>Editing Train</h1>

<%= render 'form', train: @train %>

<%= link_to 'Show', [:admin, @train] %> |
<%= link_to 'Back', admin_trains_path %>

app/views/admin/trains/index.html.erb
<h1>Trains</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @trains %>
  </tbody>
</table>

<br>

<%= link_to 'New Train', new_admin_train_path %>

app/views/admin/trains/new.html.erb
<h1>New Train</h1>

<%= render 'form', train: @train %>

<%= link_to 'Back', admin_trains_path %>

app/views/admin/trains/show.html.erb
<p>
  <strong>Number:</strong>
  <%= @train.number %>
  </br>
</p>
<p>
  <strong>On station:</strong>
  <% if @train.current_station.present? %>
    <%= @train.current_station.title %>
  <% else %>
    Not set
  <% end %>
</p>
<p>
  <strong>Train's route:</strong>
  <% if @train.route.present? %>
    <%= @train.route.name %>
  <% else %>
    Train hasnt got any route
  <% end %>
</p>

<p>
  <% if @train.cars.present? %>
    <p>
      <strong>List of cars cars:</strong>
      <% if @train.ordering %>
        <% @train.cars.asc.each do |car| %>
          <%= link_to "#{car.number}", [:admin, car] %>
        <% end %>
      <% else %>
        <% @train.cars.desc.each do |car| %>
          <%= link_to "#{car.number}", [:admin, car] %>
        <% end %>
      <% end %>
    </p>
  <% else %>
    Train hasnt got any cars
  <% end %>
</p>

<p>
  <%= link_to "Add car", new_admin_train_car_path(@train) %>
</p>


<%= link_to 'Edit', edit_admin_train_path(@train) %> |
<%= link_to 'Back', admin_trains_path %>