config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resource :search, only: [:show, :create]
  # resource :ticket, only: [:show, :create, :new]
  resources :tickets

  namespace :admin do
    resources :railway_stations do
      patch :update_station_order, on: :member
      patch :update_time, on: :member
    end

    resources :trains do
      resources :cars, shallow: true
    end

    resources :routes
    resources :tickets
  end

  get 'welcome/index'
  root 'searches#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :train

  validates :car_type, :number, presence: true
  validates :number, uniqueness: { scope: :train_id }

  scope :asc, -> { order(:number) }
  scope :desc, -> { order('number DESC') }
  scope :plazkart, -> { where(car_type: 'PlazkartCar') }
  scope :coupe, -> { where(car_type: 'CoupeCar') }
  scope :SV, -> { where(car_type: 'SVCar') }
  scope :seat, -> { where(car_type: 'SeatCar') }

  before_validation :set_number

  private

  def set_number
    numb = Car.where(train_id: train).maximum(:number)
    self.number = numb ? numb + 1 : 1
  end

end

app/models/coupe_car.rb
class CoupeCar < SvCar
  validates :up_space, presence: true, numericality: { only_integer: true }
end

app/models/plazkart_car.rb
class PlazkartCar < CoupeCar
  validates :side_up_space, :side_low_space, presence: true, numericality: { only_integer: true }
end

app/models/railway_station.rb
class RailwayStation < ApplicationRecord
  has_many :trains
  has_many :railway_stations_routes
  has_many :routes, through: :railway_stations_routes

  validates :title, presence: true
  scope :ordered, -> {
                    joins(:routes).where('routes.id=railway_stations_routes.route_id')
                                  .order('railway_stations_routes.station_order') 
  }

  def update_station_order(route, order)
    temp_station_order = station(route)
    temp_station_order.update(station_order: order) if temp_station_order
  end

  def position_in(route)
    station(route).try(:station_order)
  end

  def update_time(route, arrival, departure)    
    temp_station = station(route)
    temp_station.update(arrival: arrival) if temp_station
    temp_station.update(departure: departure) if temp_station
  end

  def station_time(route, time)
    station(route).try(time)
  end

  protected

  def station(route)
    @station ||= railway_stations_routes.where(route: route).first
  end
end

app/models/railway_stations_route.rb
class RailwayStationsRoute < ApplicationRecord
  belongs_to :railway_station
  belongs_to :route

  validates :railway_station_id, uniqueness: { scope: :route_id }
end

app/models/route.rb
class Route < ApplicationRecord
  has_many :railway_stations_routes
  has_many :railway_stations, through: :railway_stations_routes
  has_many :trains

  validates :name, presence: true
  validate :stations_count


  before_validation :set_name

  # default_scope { joins(:railway_stations_routes) }

  private

  def set_name
    self.name = "#{railway_stations.first.title} - #{railway_stations.last.title}"
  end

  def stations_count
    if railway_stations.size < 2
      errors.add(:base, 'Route should contain at least 2 stations')
    end
  end
end

app/models/search.rb
class Search

  include ActiveModel::Model

  attr_accessor :start_station_id, :end_station_id
  attr_reader :search_result

  def find_start_station
    @start_station ||= RailwayStation.find(start_station_id)
  end

  def find_end_station
    @end_station ||= RailwayStation.find(end_station_id)
  end

  def do_search
    @search_result = Train.includes(route: :railway_stations).where(railway_stations: { id: start_station_id }) &
                     Train.includes(route: :railway_stations).where(railway_stations: { id: end_station_id })
  end

end

app/models/seat_car.rb
class SeatCar < Car
  validates :seat_space, presence: true, numericality: { only_integer: true }
end

app/models/sv_car.rb
class SvCar < Car
  validates :low_space, presence: true, numericality: { only_integer: true }
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user
  belongs_to :train
  belongs_to :start_station, class_name: 'RailwayStation', foreign_key: :start_station_id
  belongs_to :end_station, class_name: 'RailwayStation', foreign_key: :end_station_id

  validates :pas_name, :pas_pasport, presence: true

  after_create :send_notification
  after_destroy :send_notification_destroy

  def route_name
    "#{start_station.title} - #{end_station.title}"
  end

  private

  def send_notification
    TicketsMailer.buy_ticket(self.user, self).deliver_now
  end

  def send_notification_destroy
    TicketsMailer.delete_ticket(self.user, self).deliver_now
  end
end

app/models/train.rb
class Train < ApplicationRecord
  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id
  belongs_to :route
  has_many :tickets
  has_many :cars

  validates :number, presence: true

  private

  # where shoul we use it in our app?
  # in view?
  def count_type_place(type, space_type)
    count = Car.where(car_type: "#{type}").sum(:space_type)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :validatable
  has_many :tickets

  validates :first_name, :second_name, presence: true
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def show
    @search ||= Search.new
  end

  def create
    @search = Search.new(search_params)
    @search.do_search
    render :show
  end

  protected

  def search_params
    params.require(:search).permit(:start_station_id, :end_station_id)
  end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!, only: :create
  before_action :hidden_params, only: [:new]
  before_action :set_ticket, only: [:show]

  def index
    @tickets = current_user.tickets
  end

  def show
  end

  def create
    @ticket = current_user.tickets.new(ticket_params)
    if @ticket.save
      redirect_to @ticket
    else
      render :new
    end
  end

  def new
    @ticket = Ticket.new(train_id: params[:train_id], start_station_id: params[:start_station_id], end_station_id: params[:end_station_id])
  end

  def destroy
    set_ticket.destroy
    redirect_to tickets_path, notice: 'Ticket was successfully destroyed.'
  end

  private

  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  def ticket_params
    params.require(:ticket).permit(:train_id, :start_station_id, :end_station_id, :pas_name, :pas_pasport)
  end

  def hidden_params
    @train = Train.find(params[:train_id])
    @start_station = RailwayStation.find(params[:start_station_id])
    @end_station = RailwayStation.find(params[:end_station_id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/railway_stations_helper.rb
module RailwayStationsHelper
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_errors.html.erb
  <% if resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= t('common.errors') %></h2>

      <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Trains" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Trains</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
          <% if user_signed_in? %>
            <li><%= link_to "Выйти", destroy_user_session_path, method: :delete  %></li>
            <% if current_user.admin? %>
              <li><%= link_to "Админка", admin_railway_stations_path  %></li>
            <% end %>
          <% else %>
            <li><%= link_to "Войти", new_user_session_path  %></li>
          <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>Author: Zolotukhin Andrei.
Training project in <a href="http://thinknetica.com">online school Thinknetica</a></p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/ticpart/_form.html.erb
<%= form_for(ticket) do |f| %>
  <%= render 'common/errors', resource: ticket %>

  <%= f.hidden_field :train_id %>
  <%= f.hidden_field :start_station_id %>
  <%= f.hidden_field :end_station_id %>

  <div class="field">
    <%= f.label :pas_name, "Passenger name" %>
    <%= f.text_field :pas_name %>
  </div>

  <div class="field">
    <%= f.label :pas_pasport, "Passenger pasport" %>
    <%= f.text_field :pas_pasport %>
  </div>

  <div class="actions">
    <%= f.submit "#{ticket.new_record? ? "Buy ticket" : 'Update' }" %>
  </div>
<% end %>

app/views/ticpart/_show.html.erb
<h1><%= t('tickets.show.ticket_info') %></h1>

<p><%= t('ticketinfo.owner') %>: <%= @ticket.user.email %></p>

<p><%= t('ticketinfo.tr_number') %>: <%= @ticket.train.number %></p>

<p><%= t('ticketinfo.departure_station') %>: <%= @ticket.start_station.title %></p>

<p><%= t('ticketinfo.arrival_station') %>: <%= @ticket.end_station.title %></p>

<p><%= t('ticketinfo.pas_name') %>: <%= @ticket.pas_name %></p>

<p><%= t('ticketinfo.pas_pasport') %>: <%= @ticket.pas_pasport %></p>

<% if current_user.admin? %>
  <%= link_to t('admin.tickets.show.to_tickets_list'), admin_tickets_path %>
<% else %>
  <%= link_to  t('tickets.show.to_tickets_list') , tickets_path %>
<% end %>

app/views/ticpart/_ticket.html.erb
<tr>
  <td><%= t('ticketinfo.tr_number') %>: <%= ticket.train.number %></td>
  
  <% if current_user.admin? %>
    <td><%= link_to t('common.show'), admin_ticket_path(ticket) %></td>
    <td><%= link_to t('common.edit'), edit_admin_ticket_path(ticket) %></td>
    <td><%= link_to t('common.destroy'), admin_ticket_path(ticket), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  <% else %>
    <td><%= link_to t('common.show'),  ticket %></td>
    <td><%= link_to t('common.destroy'), ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  <% end %>
  
</tr>